### ISSUE TITLE
"Stop using vert.x" roadmap

### ISSUE THREAD

**Issue by queer** [mewna/catnip#289]
As we've talked about this a lot in the Discord server, and have a couple branches here that experiment with getting rid of it, this issue will track everything that we need to do in order for this to happen, so that we can actually have an authoritative source for it. This list will be updated as time goes on.

Since the main branch being developed is called `fuck-vertx` you can tell how we feel about Vert.x at times :sweat_smile:

- [x] Require Java 11. See the `fuck-vertx` branch
- [x] Convert REST to use the J9+ HTTP client. See the `fuck-vertx` branch
- [x] Convert shards to use the J9+ HTTP client. See the `fuck-vertx` branch
- [ ] Real solution for event loops, timed/repeating task scheduling, ...
- [ ] Preferably not do massive breaking changes. #287 is making this look difficult
- [ ] Preferably start using immutables.org. See #287 
- [ ] Figure out a decent alternative lib for JSON handling
- [ ] Preferably decompose `CatnipShard` and event buffers into more-testable/composable units. See #261 
- [ ] Real solution for moving non-guild/user events off of the main event loops, to avoid blocking shard lifecycle events and caching. See #227 
- [ ] Real solution for things that need blocking handling, like the initial `GUILD_CREATE` events. See #227 
- [ ] Get a real replacement for verticles for shards and extensions
- [x] ~~Choose a real Reactive:tm: library to use (rx or Project Reactor or ...) instead of vert.x.~~ ~~Looks like we're RxJava2~~ RxJava2 merged into master in 0d1fa8469c32f3931a7d2edbd901ec04d0da91bb
- [ ] Still allow using `Catnip#on` for backwards compatibility
- [x] ~~Update `LogAdapter` to use the stack walking API. See #287~~ Done as of 12dba2333b09991322c92235c28331ab15a791ff

**Comment by KJP12** [comment]
First three can be tagged off with `fuck-vertx` and PR #277, being as it enforces those three requirements.

**Comment by Stupremee** [comment]
What about RxJava2 for reactive library?

**Comment by queer** [comment]
Rx2 is my current thought; see #288

**Comment by adriantodt** [comment]
> What about RxJava2 for reactive library?

Both RxJava2 and ReactiveStreams are quite nice libs imo. I personally prefer ReactiveStreams but in my opinion we should let this to be chosen by amy (before this turns into a holy grail war)

Also, while I prefer RS, probably Catnip will use Rx because:

- There's already a RX extension
- D4J uses ReactiveStreams, so Catnip would be either shadowing or being shadowed by another RS-based Discord lib
- RX have a [RS interop](https://github.com/ReactiveX/RxJavaReactiveStreams) so in any case stuff is as simple as a "catnip-reactivestreams" extension

If anything to consider about using ReactiveStreams:

- We're going after updating to J11+. ReactiveStreams use a 1:1-ish API that adapts to J9's java.util.concurrent.Flow
  - The new HttpClient uses that API iirc.
  - Adopting ReactiveStreams would make the codebase look rather uniform. And that's good.
- The RX argument "but it works on Android" is made useless because we're migrating to J11.
- (personal opinion) ReactiveStreams API are much "generalized" when RxJava has a lot of "specialized use-cases" stuff. This can be either good or bad but most of the times users get confused.

...

> Rx2 is my current thought; see #288

amy you sent it while I was writing this

_at least I guess there'll be no further discussion._

**Comment by queer** [comment]
Hey, I'm open to RS if there's a good argument for it, but the "D4J already uses it" thing seems like a good reason to do something different :P

**Comment by Stupremee** [comment]
What about [Jsoniter](https://github.com/json-iterator/java) as a JSON Library?

**Comment by adriantodt** [comment]
> Figure out a decent alternative lib for JSON handling

As the [Java JSON JEP](https://openjdk.java.net/jeps/198) is still lost in time I'd use [org.json](https://github.com/stleary/JSON-java) library as it's the lighter, simpler and would require the less amount of changes possible from vert.x JSON stuff (V.x JsonObject is basically org.JSON JSONObject but half-fluent)

**Comment by queer** [comment]
If #300 works out, then we can put off dealing with #287 / #163, which would be nice given how much of a mess #287 has become. I think that would be the preferable option for now, unless someone wants to do all the heavy lifting on that Q_Q

**Comment by GrandPanda** [comment]
To clear up some misinformation in this thread (not that it matters really): 

I assume by "ReactiveStreams" you mean [reactive-streams](http://www.reactive-streams.org/). This is *not* a "lib" at all comparable to RxJava or Reactor. It is a specification. It is simply a standard set of interfaces and rules for implementing systems adhering to the ideas presented in the [Reactive Manifesto](https://www.reactivemanifesto.org/). 

JDK9's `Flow` is an adoption of these standardized interfaces into the JDK. It is a namespace change, nothing more. It is *exactly* 1:1.

Implementing these interfaces properly is *very* difficult. There's a lot of [rules](https://github.com/reactive-streams/reactive-streams-jvm#specification) to follow and tests to pass. They exist solely to serve as a basis for interoperability between higher level libraries like RxJava 2, Reactor 3, akka-streams, and more. They allow you to easily operate across library boundaries. All of these libraries depend on reactive-streams. (These higher level libraries can be classified into "[generations](https://github.com/ReactiveX/RxJava/wiki/Writing-operators-for-2.0#generations)." Those which depend on reactive-streams are at least third generation.) These kinds of libraries are the ones you pick from, not reactive-streams. 

Discord4J uses Reactor 3 for its reactive library. If the goal is "don't do what Discord4J does" (though I don't think that's a useful ideology) then that's the one to avoid. So, while the statement "D4J uses ReactiveStreams" is not technically incorrect (because Reactor depends on it), it's missing *a lot*.

**Comment by queer** [comment]
@GrandPanda I have a bad habit of using "reactive-streams" to refer to both what it actually is as well as Project Reactor >~<

**Comment by queer** [comment]
@GrandPanda The idea isn't "don't do what D4J does" inasmuch as "try to write the lib that I personally want to use." Having played with both, I've found that I tend to prefer Rx to Reactor. I do understand what `reactive-streams` is; I just have a very bad habit of using that term to also refer to Reactor. :sweat:

**Comment by queer** [comment]
Closed in favour of #326
